propriedades_rurais_nomes = [
    "Sítio Boa Vista",
    "Chácara Bela Vista",
    "Sítio Recanto Feliz",
    "Chácara Paraíso Verde",
    "Sítio Estrela do Norte",
    "Chácara Vale Encantado",
    "Sítio Pôr do Sol",
    "Chácara Lagoa Serena",
    "Sítio Campo Belo",
    "Chácara Terra Prometida",
    "Sítio Monte Alegre",
    "Chácara Rio Claro",
    "Sítio Bosque Encantado",
    "Chácara Jardim das Flores",
    "Sítio Vale dos Sonhos",
    "Chácara Estância da Paz",
    "Sítio Rancho Alegre",
    "Chácara Serra Dourada",
    "Sítio Campo Verde",
    "Chácara Vale do Sol",
    "Sítio Recanto das Águas",
    "Chácara Terra Nova",
    "Sítio Vista Alegre",
    "Chácara Vale do Silêncio",
    "Sítio Estância do Sossego",
    "Chácara Rancho do Sol",
    "Sítio Serra Azul",
    "Chácara Campo Sereno",
    "Sítio Vale do Encanto",
    "Chácara Recanto do Paraíso",
    "Sítio Terra do Sol",
    "Chácara Vista do Horizonte",
    "Sítio Vale da Esperança",
    "Chácara Estância do Horizonte",
    "Sítio Rancho do Vale",
    "Chácara Serra Verde",
    "Sítio Campo do Céu",
    "Chácara Vale das Estrelas",
    "Sítio Recanto do Sol",
    "Chácara Terra Encantada",
    "Sítio Vista do Vale",
    "Chácara Vale da Paz",
    "Sítio Estância do Sol",
    "Chácara Rancho do Horizonte",
    "Sítio Serra do Encanto",
    "Chácara Campo do Sol",
    "Sítio Vale do Horizonte",
    "Chácara Recanto do Encanto",
    "Sítio Terra das Flores",
    "Chácara Vista do Paraíso",
    "Fazenda Sol Nascente",
    "Fazenda Estrela Guia",
    "Fazenda Horizonte Azul",
    "Fazenda Vale Encantado",
    "Fazenda Paraíso Verde",
    "Fazenda Recanto Feliz",
    "Fazenda Pôr do Sol",
    "Fazenda Lagoa Serena",
    "Fazenda Campo Belo",
    "Fazenda Terra Prometida",
    "Fazenda Monte Alegre",
    "Fazenda Rio Claro",
    "Fazenda Bosque Encantado",
    "Fazenda Jardim das Flores",
    "Fazenda Vale dos Sonhos",
    "Fazenda Estância da Paz",
    "Fazenda Rancho Alegre",
    "Fazenda Serra Dourada",
    "Fazenda Campo Verde",
    "Fazenda Vale do Sol",
    "Fazenda Recanto das Águas",
    "Fazenda Terra Nova",
    "Fazenda Vista Alegre",
    "Fazenda Vale do Silêncio",
    "Fazenda Estância do Sossego",
    "Fazenda Rancho do Sol",
    "Fazenda Serra Azul",
    "Fazenda Campo Sereno",
    "Fazenda Vale do Encanto",
    "Fazenda Recanto do Paraíso",
    "Fazenda Terra do Sol",
    "Fazenda Vista do Horizonte",
    "Fazenda Vale da Esperança",
    "Fazenda Estância do Horizonte",
    "Fazenda Rancho do Vale",
    "Fazenda Serra Verde",
    "Fazenda Campo do Céu",
    "Fazenda Vale das Estrelas",
    "Fazenda Recanto do Sol",
    "Fazenda Terra Encantada",
    "Fazenda Vista do Vale",
    "Fazenda Vale da Paz",
    "Fazenda Estância do Sol",
    "Fazenda Rancho do Horizonte",
    "Fazenda Serra do Encanto",
    "Fazenda Campo do Sol",
    "Fazenda Vale do Horizonte",
    "Fazenda Recanto do Encanto",
    "Fazenda Terra das Flores",
    "Fazenda Vista do Paraíso",
]
