# Generated by Django 5.1.2 on 2024-10-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('area_total', models.FloatField()),
                ('area_agricultavel', models.FloatField()),
                ('area_vegetacao', models.FloatField()),
                ('culturas', models.CharField(max_length=255)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fazendas', to='produtor_rural.produtorrural')),
            ],
        ),
    ]
