# Generated by Django 5.1.2 on 2024-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor_rural', '0002_alter_fazenda_culturas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazenda',
            name='culturas',
            field=models.TextField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('algodao', 'Algodão'), ('cafe', 'Café'), ('cana', 'Cana de Açúcar')]),
        ),
    ]
