# Generated by Django 5.1.2 on 2024-10-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtor_rural', '0003_alter_fazenda_culturas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazenda',
            name='culturas',
            field=models.TextField(),
        ),
    ]
